# Generated by Django 3.1 on 2022-02-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220217_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Public address'),
        ),
    ]
