# Generated by Django 3.1 on 2022-02-17 08:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=250, verbose_name='Owner Full Name')),
                ('state', models.CharField(max_length=200, null=True, verbose_name='State')),
                ('district', models.CharField(max_length=200, verbose_name='District')),
                ('municiplity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Municiplity')),
                ('village', models.CharField(blank=True, max_length=200, null=True, verbose_name='Village')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('contact_no', models.CharField(max_length=250, verbose_name='Contact Number')),
                ('coordinate', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), size=2)),
                ('area', models.FloatField(max_length=50, verbose_name='Area in Sqr ft')),
                ('sha256', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sha256')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
