# Generated by Django 3.1.7 on 2021-03-08 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='coordinate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), size=2),
        ),
    ]
