# Generated by Django 3.1 on 2022-02-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_property_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
