# Generated by Django 3.1 on 2022-03-15 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_property_survey_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='survey_no',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Survey Number'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('prty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='land.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
            },
        ),
    ]
